# Generated by Django 4.0 on 2022-11-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_passdata_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annoucement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Annoucement_title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='tender')),
                ('attached_file', models.FileField(null=True, upload_to='tender')),
                ('put_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
