# Generated by Django 4.0 on 2022-11-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_annoucement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childdata',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100),
        ),
    ]
