# Generated by Django 4.0 on 2022-11-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_childdata_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childdata',
            name='Gender',
        ),
    ]
