# Generated by Django 4.0 on 2022-11-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_childdata_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdata',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='childdata'),
        ),
    ]
