# Generated by Django 4.0 on 2022-11-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_childdata_birth_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childdata',
            name='birth_certificate',
        ),
    ]
