# Generated by Django 4.0 on 2022-11-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_childdata_birth_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucement',
            name='Description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
